### ISSUE TITLE
Fix dialyzer errors

### ISSUE THREAD

**Issue by hectorperez** [notesclub/notesclub#105]
When we run `mix dialyzer` we get a few errors. We should fix this.

**Comment by dmarcoux** [comment]
It would be also nice to run dialyzer in the CI. I will have a look at this in the upcoming days.

**Comment by hectorperez** [comment]
Yeah, when `mix dialyzer` errors are fixed it would be great to add it to the CI.

**Comment by dmarcoux** [comment]
There are some type errors for the Ecto schemas and I realize now that I made a mistake in this [commit](https://github.com/notesclub/notesclub/pull/107/commits/2f4b35fdd947795022dc1e93cfdcd3dea5a4f914). We will have to add types to those Ecto schemas. While this can be done manually as explained [here](https://hexdocs.pm/ecto/Ecto.Schema.html#module-working-with-typespecs) upstream, I would favor using [typed_ecto_schema](https://github.com/bamorim/typed_ecto_schema), which handles this in a much better and simpler way than having to manually write those types over and over again with a lot of duplicated code.

I could do this in the next days if you would like @hectorperez.

**Comment by hectorperez** [comment]
@dmarcoux that would be great, thanks Dany. `typed_ecto_schema` looks good.

**Comment by dmarcoux** [comment]
I don't plan on fixing the remaining Dialyzer errors, so this issue is free again.

**Comment by hectorperez** [comment]
Sounds good, thank you for your help @dmarcoux!
