### ISSUE TITLE
Log in with GitHub

### ISSUE THREAD

**Issue by hectorperez** [notesclub/notesclub#127]
We'd like to be able to log in with our GitHub account.

Later, in different issues, we'll use this to like notebooks and add comments.

**Comment by fabrithedev** [comment]
Hello @hectorperez 

I'll try to take a look on this one tomorrow!

**Comment by hectorperez** [comment]
Sure @FabriDamazio, thanks!

**Comment by fabrithedev** [comment]
@hectorperez 

"I’ve completed the initial implementation using the `:elixir_auth_github` library, and it’s available on my fork. The ‘Sign in with GitHub’ button has been added to the index liveview. Please feel free to enhance the visual design.

![image](https://github.com/notesclub/notesclub/assets/3181570/d247632c-be8e-46b0-b5dd-863884b07b7a)


Now, we need to decide which user data we should persist in our database. Here’s a sample of the login response—a map containing GitHub user details and an access token:

```elixir
%{
  site_admin: false,
  disk_usage: 265154,
  access_token: "8eeb143935d1a505692aaef856db9b4da8245f3c",
  private_gists: 0,
  followers_url: "https://api.github.com/users/nelsonic/followers",
  public_repos: 291,
  gists_url: "https://api.github.com/users/nelsonic/gists{/gist_id}",
  subscriptions_url: "https://api.github.com/users/nelsonic/subscriptions",
  plan: %{
    "collaborators" => 0,
    "name" => "pro",
    "private_repos" => 9999,
    "space" => 976562499
  },
  node_id: "MDQ6VXNlcjE5NDQwMA==",
  created_at: "2010-02-02T08:44:49Z",
  blog: "http://www.dwyl.io/",
  type: "User",
  bio: "Learn something new every day. github.com/dwyl/?q=learn",
  following_url: "https://api.github.com/users/nelsonic/following{/other_user}",
  repos_url: "https://api.github.com/users/nelsonic/repos",
  total_private_repos: 5,
  html_url: "https://github.com/nelsonic",
  public_gists: 29,
  avatar_url: "https://avatars3.githubusercontent.com/u/194400?v=4",
  organizations_url: "https://api.github.com/users/nelsonic/orgs",
  url: "https://api.github.com/users/nelsonic",
  followers: 2778,
  updated_at: "2020-02-01T21:14:20Z",
  location: "London",
  hireable: nil,
  name: "Nelson",
  owned_private_repos: 5,
  company: "@dwyl",
  email: "nelson@gmail.com",
  two_factor_authentication: true,
  starred_url: "https://api.github.com/users/nelsonic/starred{/owner}{/repo}",
  id: 194400,
  following: 173,
  login: "nelsonic",
  collaborators: 8,
  scope: "repo,user:email"
}
```

**Comment by hectorperez** [comment]
@FabriDamazio I would persist the following fields in the existent `users` table:
- `id` -> `github_id`
- `name` -> `name`
- `bio` -> `bio`
- `email` -> `email`
- `location` -> `location`
- `followers` -> `followers_count`

If you can, please also add a column called `last_login_at` with the time of the last login.

Would you add anything else? Thanks!

**Comment by hectorperez** [comment]
By the way, the visual design is good. I'd just add round borders to the button like the other buttons in the page. Thanks!

**Comment by fabrithedev** [comment]
> By the way, the visual design is good. I'd just add round borders to the button like the other buttons in the page. Thanks!

Changes made. Looking good! 😊 The rest, I’ll look at during the week!

![image](https://github.com/notesclub/notesclub/assets/3181570/9a767f5b-a8c6-479e-8c33-6a8585e37cb5)

**Comment by fabrithedev** [comment]
A small update:

[x] Changed `elixir_auth_github` to `ueberauth` to keep the implementation extensible for other providers. Also, it’s a library that is more widely used and battle-tested.
[x] Login functionality (including design, user creation, plug, and session management).
[ ] Logout functionality.
[ ] New user fields

**Comment by hectorperez** [comment]
Sounds good!

By the way, when a user already exists, we don't create a new record in the users table, do it?
Thanks!

**Comment by fabrithedev** [comment]
> Sounds good!
> 
> By the way, when a user already exists, we don't create a new record in the users table, do it? Thanks!

No, just if he is a new user.

**Comment by fabrithedev** [comment]
@hectorperez 

Can you please check the current implementation at: https://github.com/FabriDamazio/notesclub/commit/41786ee460074c0fa540551cef01443b564fdf1d

(the instructions to run in development is on the readme file)

After your review i will procced with the  new user fields.

**Comment by hectorperez** [comment]
Great job @FabriDamazio! 🚀 

I left two comments in your commit.

**Comment by fabrithedev** [comment]
Ok, everything is good and working!
Tomorrow I'll finish all the working adding the new user fields and i think it's ready to open a PR. Ty for the support @hectorperez
