### ISSUE TITLE
[Question] Regarding Repo?

### ISSUE THREAD

**Issue by apoorv-2204** [notesclub/notesclub#15]
Hello, 
Can we have a small brief info about repo code, just to get kick stated. :)

**Comment by hectorperez** [comment]
Hi,
At the moment we have two tables: notebooks and searches. Soon we'll have users and repos too.

Also, we use https://github.com/notesclub/notesclub/blob/main/lib/notesclub/searches/populate.ex and https://github.com/notesclub/notesclub/blob/main/lib/notesclub/searches/fetch.ex to download and save new notebooks from Github.

Is it a bit clearer now?

**Comment by hectorperez** [comment]
We could document this. Maybe in the README.
