### ISSUE TITLE
Development setup issue

### ISSUE THREAD

**Issue by aayushmau5** [notesclub/notesclub#165]
Hi! I have been trying to set up this project locally, however I'm not sure how to download the notebooks. I have added github API key in `config/dev.secret.exs` file but now sure what to do next? 

Any help is appreciated. Thanks!

**Comment by hectorperez** [comment]
Hi Aayush!

Do you mean to download notebooks from GitHub? If so, have a look at
RecentNotebooksWorker.

Yet, to run most of the application locally you can use a the seed file.
When you run “mix ecto.setup” it also loads some example notebooks in your
database.

Does this answer your question?

**Comment by aayushmau5** [comment]
> Yet, to run most of the application locally you can use a the seed file.
When you run “mix ecto.setup” it also loads some example notebooks in your
database.

Tried this however I'm not seeing any entry on the homepage. It tells me there are 7 notebooks though.

![image](https://github.com/notesclub/notesclub/assets/54525741/30f04f4c-9d45-4147-9142-e3e561a98f54)

**Comment by hectorperez** [comment]
I just fixed the [seed files](https://github.com/notesclub/notesclub/pull/168/files).

Please do a git pull from master and run `mix ecto.drop` and `mix ecto.setup` and it should work now.

Btw, your [PR](https://github.com/notesclub/notesclub/pull/166) was great and it is in production now, thanks!! 🚀

**Comment by hectorperez** [comment]
@aayushmau5 I just fixed the [seed files](https://github.com/notesclub/notesclub/pull/168/files).

Please do a git pull from master and run `mix ecto.drop` and `mix ecto.setup` and it should work now.

Btw, your [PR](https://github.com/notesclub/notesclub/pull/166) was great and it is in production now, thanks!! 🚀

**Comment by hectorperez** [comment]
@aayushmau5 If you still have any problem with the seeds after my changes, please reopen this issue. Thanks!!

**Comment by aayushmau5** [comment]
Just tried it. It's working as intended. Thanks for the quick fix!
