### ISSUE TITLE
Add popularity column to notebooks

### ISSUE THREAD

**Issue by hectorperez** [notesclub/notesclub#172]
Add a column called `popularity` or similar to the table notebooks. The default value should be zero.

Then, when someone clicks on “Run in Livebook” or on the link to GitHub on a notebook page such as [this one](https://notes.club/livebook-dev/nerves_livebook/priv/samples/tflite), increase `popularity` by one.

This was proposed by [Rick_Morin in the elixirforum](https://elixirforum.com/t/notesclub-discover-livebook-notebooks/49698/9) to track the interest in notebooks. Thanks!

**Comment by tanavdev** [comment]
i can try to do this one, this is my first contribution so please understand
