### ISSUE TITLE
Autocomplete tags/links to other notes in edit mode + multiline textarea

### ISSUE THREAD

**Issue by hectorperez** [notesclub/notesclub#19]
It should autosuggest other notes from the same logged-in user, no need for notes from other users at the moment.

We probably could use https://github.com/webscopeio/react-textarea-autocomplete

The text area should dynamically adjust the number of rows depending on the text.

**Comment by AlvaroMaceda** [comment]
Here is a link for adjusting height automatically: https://stackoverflow.com/questions/17772260/textarea-auto-height
