### ISSUE TITLE
Add Twitter/X icon to share notebook

### ISSUE THREAD

**Issue by hectorperez** [notesclub/notesclub#193]
On a notebook page (e.g. [this](https://notes.club/josevalim/livebooks/talks/2023/04-elixir-conf)), we'd like to include an X icon that when we click it, it opens a new tab on X with the text "notebook title by @x_username (or user name) + link to notebook on notesclub #myelixirstatus".

We can copy this component:
- https://github.com/youcongress/youcongress/blob/main/lib/you_congress_web/live/voting_live/show/share_component.ex#L14

**Comment by hectorperez** [comment]
Assigned to @henrezende. GitHub doesn't let me to assign it until Henrique comments in the issue, despite he already has a PR.

**Comment by henrezende** [comment]
> Assigned to @henrezende. GitHub doesn't let me to assign it until Henrique comments in the issue, despite he already has a PR.

Thanks! :D
