### ISSUE TITLE
Sort columns

### ISSUE THREAD

**Issue by hectorperez** [notesclub/notesclub#2]
When a visitor clicks on the headers:
- Author: it sort notebooks by github_owner_login
- Repo: it sort notebooks by github_repo_name
- Filename: it sorts notebooks by github_filename

For example, we could use a URL parameter: ...?filter=author

**Comment by fabrithedev** [comment]
Hey @hectorperez 
Can i try this one?

**Comment by hectorperez** [comment]
Hi @FabriDamazio!

I'm just considering replacing the controller with LiveView.
If we do so, maybe it's worth to wait for this issue.

What do you think? Would you like us to use LiveView for notes.club?

**Comment by fabrithedev** [comment]
> Hi @FabriDamazio!
> 
> I'm just considering replacing the controller with LiveView. If we do so, maybe it's worth to wait for this issue.
> 
> What do you think? Would you like us to use LiveView for notes.club?

For me the application is pretty decent without LiveView but i think we can move to it.
I can try the replacing and then implement sorting if its ok to you

**Comment by hectorperez** [comment]
That's would be awesome, thanks!

I created an issue for LiveView: https://github.com/notesclub/notesclub/issues/59
Please leave a message there so I can assign you that issue too.

**Comment by hectorperez** [comment]
@FabriDamazio that would be awesome, thanks!

I created an issue for LiveView: https://github.com/notesclub/notesclub/issues/59
Please leave a message there so I can assign you that issue too.

**Comment by hectorperez** [comment]
We don't have columns any more.
