### ISSUE TITLE
Delete old searches

### ISSUE THREAD

**Issue by hectorperez** [notesclub/notesclub#26]
Every week we could delete all searches older than one month.

Please confirm that the linked notebooks are nilified and not destroyed.

We could use [quantum](https://hexdocs.pm/quantum) which we already use in the project. Later we might move it to something like Oban.

**Comment by hassanRsiddiqi** [comment]
@hectorperez I would like to take this task.

**Comment by hectorperez** [comment]
@hassanRsiddiqi sure, thanks!
