### ISSUE TITLE
Create an endpoint for related notes

### ISSUE THREAD

**Issue by hectorperez** [notesclub/notesclub#38]
Create a new endpoint /notes/:id/related

It could receive (or not) the following parameters:
- include_descendants
- include_ancestors
- include_user

At the moment, related notes are those that:
- have a backlink/reference to the passed note (e.g. `where("content like %[[#{note.content}]]%")` or `where("content like %##{note.content}%")`)
- are a root note (`ancestry: nil`) and `content` is exactly `note.content`. For example, if the passed note is `/hec/favourite_books`, I want to see the notes with the same content from other users such as `/alvaro/favourite_books`.

Order:
- If there is an authenticated user (defined in method `current_user`), it should return the related notes from the authenticated user first.
- After the notes from the authenticated user, it should return the notes of the user of the passed note.

Also, it should not return the passed note (from the note.user) as a related note.

Please add some tests.

In a different ticket (so do not worry about this now), this will be used from `setReferences` in `UserNotePage.tsx`. Instead of 
`/notes`, we'll use `/notes/:id/related`.

**Comment by AlvaroMaceda** [comment]
I'm working on this, almost done.
