### ISSUE TITLE
Add infinite scroll

### ISSUE THREAD

**Issue by hectorperez** [notesclub/notesclub#42]
The homepage could return the last 30 notebooks.
Then, **as we scroll down, we should load more in an infinite scroll.**
@BrooklinJazz has a [post](https://brooklinmyers.medium.com/pagination-and-infinite-scroll-in-phoenix-d2a5f9bac5d6) about how to implement infinite scroll in liveview.

We could also:
- Get rid of `/last_week`, `/last_month` and `/all`.
- Move the `Random` button just before the table, as it is a really long table. And when we click on it, it would replace the URL with `/random`.

**Comment by BrooklinJazz** [comment]
I'm happy to give a hand on this

**Comment by hectorperez** [comment]
@FabriDamazio is changing the controller to LiveView https://github.com/notesclub/notesclub/issues/59.
So let's not work on the infinite scroll until that is done. Actually, it might be done there.

**Comment by BrooklinJazz** [comment]
Feel free to have someone else grab this! maybe @FabriDamazio! My plate is pretty full at the moment. Or we can work on it together next pair session.
