### ISSUE TITLE
Move to LiveView

### ISSUE THREAD

**Issue by hectorperez** [notesclub/notesclub#59]
For example, we could:
1. Order the notebooks by `inserted_at` — the last ones first.

2. Instead of the three buttons on the home page, we could have only one titled "More".
   - When we click, then it would display more notebooks in the table.
   - Then, after the first click on "More", we could have an infinite scroll. That way, when we move below, we always see more notebooks. Or as a first step, we could have the "More" button for now — and leave the infinite scroll for a different issue.

Afterwards, in a different issue, we could add a "Random" button like the one we have right now.

**Comment by hectorperez** [comment]
Hi @FabriDamazio, feel free to take this issue as you proposed. Thanks!
If you have any questions, please let me know.
Also, if you have a better idea of how notes.club should list the notebooks, I'm all ears.

Please leave a message here so I can assign the issue to you. Consider it yours if you'd like to take it. Thank you!

**Comment by fabrithedev** [comment]
@hectorperez i'll try few things here and back to you with the results!

**Comment by hectorperez** [comment]
@FabriDamazio that's brilliant. Please let me know if I can help.

**Comment by fabrithedev** [comment]
Just to update the progress, everything is migrated and working fine except the search url updates (i didn't finished yet). Planning to finish it in 3 days.

**Comment by hectorperez** [comment]
@FabriDamazio that's awesome. Thanks for the update!

**Comment by fabrithedev** [comment]
Just finished today. It was faster than i expected! ;)

**Comment by hectorperez** [comment]
It's in in production now. Thank you, @FabriDamazio!! 🧡
