### ISSUE TITLE
Add .tool-versions file

### ISSUE THREAD

**Issue by digzom** [notesclub/notesclub#63]
ASDF is well adopted by Elixir community. It would be useful to have a .tool-versions in the root directory to ease the setup.

**Comment by hectorperez** [comment]
@digzom good idea.

Actually, I already have a `.tool-versions` file on my local computer [1]. But I don't know why [.gitignore](https://github.com/notesclub/notesclub/blob/main/.gitignore) is ignoring it.

Any idea? 

[1]
```
erlang 25.0.3
elixir 1.13.4
```

**Comment by digzom** [comment]
Have no idea. Maybe a global config?

In my local setup it is not being ignored. Can I create a PR with that?

**Comment by hectorperez** [comment]
@digzom sure, you can create a PR. Thanks!

**Comment by digzom** [comment]
In the mix file we have Elixir 1.12 described in project block, wich is compiled with Erlang 22.

It's ok to put these versions? Or should I take yours?

**Comment by hectorperez** [comment]
Please take Elixir 1.13.4 and Erlang 25.0.3 as they are also the versions used in [production](https://github.com/notesclub/notesclub/blob/main/Dockerfile#L15).

We should also update the mix file.

@digzom Good catch! Thanks!

**Comment by digzom** [comment]
You're welcome! I will do it right now.

**Comment by hectorperez** [comment]
All done, @digzom thanks!

**Comment by hectorperez** [comment]
Btw, my issue with the global config was that my global `.gitignore` was in a different place than I remembered.
