### ISSUE TITLE
Fetch names and twitter usernames from GitHub API

### ISSUE THREAD

**Issue by hectorperez** [notesclub/notesclub#79]
We need to fetch the twitter usernames from GitHub's API: https://docs.github.com/en/rest/users

We'll need to add a column called `twitter_username` to `users`. 
We could create `UserSyncWorker` — similar to the existent RepoSyncWorker.

This will be useful for https://github.com/notesclub/notesclub/issues/77

**Comment by DuldR** [comment]
@hectorperez I'd love to tackle this if possible! You're mainly just looking to add a call to github's API for a user's `twitter_username` correct?

**Comment by hectorperez** [comment]
@DuldR sure, all yours, thanks!

By the way, could you also add the `name` of the user?
That API endpoint returns both `twitter_username` and `name`.
So you'll need to create two columns in the table `users`. You could call them `twitter_username` and `name` too.

If you prefer to do only `twitter_username`, that's ok too, thanks!
