### ISSUE TITLE
Add Docker Compose — Development environment

### ISSUE THREAD

**Issue by dmarcoux** [notesclub/notesclub#99]
Hey,

it would be nice to have a development environment with Docker Compose, at least for the Postgres database. From the README, it's not clear which database has to be used. I found out by looking at [config/dev.exs](https://github.com/notesclub/notesclub/blob/211fb15c36999bebacba623a65d2f2452c6aa20b/config/dev.exs). This would be clearly defined in the Docker Compose file and spinning up the database would be possible with a single command.

This setup could be extended to cover everything needed to run the project.

**Comment by hectorperez** [comment]
Hi Dany! That would indeed help new contributors.

If I remember properly, we don't use anything else besides Postgres.

Feel free to do it. Otherwise, let's see if someone else wishes to help. Thanks!
